# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipmentInfo',
            new_name='ShipmentDetail',
        ),
        migrations.RenameModel(
            old_name='ShipStatus',
            new_name='ShipStat',
        ),
        migrations.RenameModel(
            old_name='StatusInfo',
            new_name='StatusDetail',
        ),
    ]
