# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170829_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='quantity',
            field=models.PositiveIntegerField(help_text='0-99', max_length=2),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='example: 0.35kg (kilograms)', max_digits=4),
        ),
    ]
