# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170829_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetail',
            name='quantity',
            field=models.PositiveIntegerField(help_text='From 0-99'),
        ),
    ]
