# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170829_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipstat',
            name='work_state',
            field=models.CharField(choices=[('a', 'Active'), ('h', 'Hold')], default='a', max_length=1),
        ),
    ]
