# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shipstat_work_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='tracking_number',
            new_name='track_id',
        ),
        migrations.RenameField(
            model_name='statusdetail',
            old_name='new_status_date',
            new_name='new_action_date',
        ),
        migrations.RemoveField(
            model_name='shipmentdetail',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='shipmentdetail',
            name='source',
        ),
        migrations.AddField(
            model_name='shipment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 12, 7, 14, 673430, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender',
            field=models.CharField(default='', help_text="sender's first and last name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='source',
            field=models.TextField(default='', help_text='Address, State, Postal Code, County'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentdetail',
            name='receiver',
            field=models.CharField(default='', help_text="receiver's first and last name", max_length=100),
            preserve_default=False,
        ),
    ]
