# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170830_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='sender',
            field=models.CharField(blank=True, help_text="sender's first and last name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='source',
            field=models.TextField(help_text='Address, State, Postal Code, County', max_length=150),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='destination',
            field=models.TextField(help_text='Address, State, Postal Code, County', max_length=150),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='dimensions',
            field=models.CharField(blank=True, help_text='0.9m x 1.5m x 3.0m', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='receiver',
            field=models.CharField(blank=True, help_text="receiver's first and last name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='ship_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_info', to='app.Shipment'),
        ),
        migrations.AlterField(
            model_name='shipstat',
            name='ship_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.Shipment'),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='ship_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to='app.Shipment'),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='this_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infostatus', to='app.ShipStat'),
        ),
    ]
