# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170830_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipmentdetail',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='new_action_date',
            field=models.DateField(),
        ),
    ]
